paginate = 5
theme = "PaperMod"
enableEmoji = true
title = "airscript.it" 
enableRobotsTXT = true
pygmentsUseClasses = true
copyright = "airscript.it"
enableInlineShortcodes = true
defaultContentLanguage = "it"
baseURL = "https://blog.airscript.it"


[languages.it]
weight = 1
languageName = "it"
languageAltTitle = "Italiano"
contentDir = "content/italian"

[languages.it.homeInfoParams]
Title = "Oh, ciao! üëãüèª"

Content = """
  Ti do il benvenuto su **airscript.it**!  
  Su questo blog troverai articoli relativi ad informatica, motivazione e molto altro!  
  Se vuoi, puoi supportarmi attraverso i link sotto o lasciando una üåü al [blog su GitHub](https://github.com/Airscripts/blog.airscript.it).  
  &nbsp;  
  Qui non si bada a spese!  
  *John Hammond, Jurassic Park.*
"""

# [[languages.it.menu.main]]
# weight = 5
# name = "Archivio"
# url = "archives/"

[[languages.it.menu.main]]
weight = 10
name = "About"
url = "about/"


[[languages.it.menu.main]]
weight = 15
name = "Cerca"
url = "search/"


[languages.en]
weight = 2
languageName = "en"
contentDir = "content/english"

# [[languages.en.menu.main]]
# weight = 5
# name = "Archive"
# url = "archives/"

[[languages.en.menu.main]]
weight = 10
name = "About"
url = "about/"

[[languages.en.menu.main]]
weight = 15
name = "Search"
url = "search/"

[languages.en.homeInfoParams]
Title = "Oh, hello! üëãüèª"

Content = """
  I welcome you on **airscript.it**!  
  On this blog you'll find articles related to computer science, motivation and much more!  
  If you want, you can support me through the link below or leaving a üåü at my [blog on GitHub](https://github.com/Airscripts/blog.airscript.it).  
  &nbsp;  
  Spared no expense!  
  *John Hammond, Jurassic Park.*
"""


[taxonomies]
tag = "tags"
category = "categories"


[params]
ShowToc = true
defaultTheme = "auto"
ShowWordCount = true
ShowReadingTime = true
label.iconWidth = "30"
label.icon = "logo.svg"
label.iconHeight = "30"
ShowShareButtons = false
images = "/logo-512x512"
displayFullLangName = true
ShowCodeCopyButtons = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/sponsors/Airscripts"

[[params.socialIcons]]
name = "KoFi"
url = "https://ko-fi.com/airscript"

[params.editPost]
appendFilePath = false
Text = "Suggest Changes"
URL = "https://github.com/Airscripts/blog.airscript.it/tree/main/content"


[outputs]
home = [ "HTML", "RSS", "JSON" ]
