paginate = 5
theme = "PaperMod"
enableEmoji = true
title = "airscript.it" 
enableRobotsTXT = true
pygmentsUseClasses = true
copyright = "airscript.it"
enableInlineShortcodes = true
defaultContentLanguage = "it"
baseURL = "https://blog.airscript.it"

[languages.it]
weight = 1
languageName = "it"
languageAltTitle = "Italiano"
contentDir = "content/italian"

description = """
Sono Francesco conosciuto come Airscript sul web e ti do un caloroso benvenuto sul mio blog!
Qui troverai articoli relativi ad open source, motivazione e molto altro.
"""

[languages.it.homeInfoParams]
Title = "Ehil√†!"

Content = """
Sono Francesco conosciuto come Airscript sul web e ti do un caloroso benvenuto sul mio blog!  
Qui troverai articoli relativi ad open source, motivazione e molto altro.  
Se vuoi, puoi supportarmi attraverso i link sotto o lasciando una stella al [blog su GitHub](https://github.com/Airscripts/blog).  
&nbsp;  
Qui non si bada a spese!  
*John Hammond, Jurassic Park.*
"""

# [[languages.it.menu.main]]
# weight = 5
# name = "Archivio"
# url = "archives/"

[[languages.it.menu.main]]
weight = 10
name = "About"
url = "about/"
pageRef = "about"
identifier = "About"

[[languages.it.menu.main]]
weight = 15
name = "Cerca"
url = "search/"
pageRef = "search"
identifier = "Search"

[languages.en]
weight = 2
languageName = "en"
languageAltTitle = "English"
contentDir = "content/english"

description = """
I am Francesco known as Airscript on the web and I warmly welcome you on my blog!  
Here you'll find articles related to open source, motivation and much more.  
"""

# [[languages.en.menu.main]]
# weight = 5
# name = "Archive"
# url = "archives/"

[[languages.en.menu.main]]
weight = 10
name = "About"
url = "about/"
pageRef = "about"
identifier = "About"

[[languages.en.menu.main]]
weight = 15
name = "Search"
url = "search/"
pageRef = "search"
identifier = "Search"

[languages.en.homeInfoParams]
Title = "Hey there!"

Content = """
I am Francesco known as Airscript on the web and I warmly welcome you on my blog!  
Here you'll find articles related to open source, motivation and much more.  
If you want, you can support me through the links below or leaving a star at my [blog on GitHub](https://github.com/Airscripts/blog.airscript.it).  
&nbsp;  
Spared no expense!  
*John Hammond, Jurassic Park.*
"""

[taxonomies]
tag = "tags"
category = "categories"

[markup]
highlight.style = "dracula"

[params]
ShowToc = true
ShowWordCount = true
label.iconWidth = 30
defaultTheme = "auto"
label.iconHeight = 30
ShowReadingTime = true
label.icon = "logo.svg"
ShowShareButtons = false
assets.disableHLJS = true
images = ["/logo-512x512"]
displayFullLangName = true
ShowCodeCopyButtons = true
assets.theme_color = "#0f94d2"
assets.msapplication_TileColor = "#2b5797"

[[customScripts]]

[[params.customStyles]]
file = "/css/offline.css"
integrity = "sha512-+R/cu1jJ/RrydyUhKhXI1QczU3TRLLLHAQyYHi1vXFAEF8lK4MxJiWgjIckiCegJ80aIB6icc6lSoLn1YY/OSA=="

[[params.notificationsScripts]]
file = "/js/notifications/dictionary.js"
integrity = "sha512-tOZZsofKwRGHAcQVGMed077Q0y4hnPvTv0Nw8L9VYWKlQgWcQZznMXZTTNID39Q0+Dumx+kHl7PlP7K+cGn6nQ=="

[[params.notificationsScripts]]
file = "/js/notifications/i18n.js"
integrity = "sha512-eNnuCLQ8noOgoy620xyZxApQlMLSJZze6Qe/h/uKQIynxfvYfmL29FimkcLho1i7AGeG+tkh0WM5pnBcIn82Hg=="

[[params.notificationsScripts]]
file = "/js/notifications/main.js"
integrity = "sha512-SAID9CBhh48e0EabUHvgvRrh2FiCmBh5Xb+fX2sv5P9IhYvRC73fYNHWg6usTYMyEOvJ6uEuP9y7nTQIgr0f7w=="

[[params.menuScripts]]
file = "/js/menu.js"
integrity = "sha512-XF6O1Z7tmFdMKJug1taoTIEN5erd8st9wgg3kujj3zIB9ErdmlzR499Eup9AKwDXeI2O6BnABt/6fWqvmzkOJw=="

[[params.socialIcons]]
name = "github"
url = "https://github.com/sponsors/Airscripts"

[[params.socialIcons]]
name = "KoFi"
url = "https://ko-fi.com/airscript"

[[params.socialIcons]]
name = "RSS"
url = "https://blog.airscript.it/index.xml"

[params.editPost]
appendFilePath = false
Text = "Suggest Changes"
URL = "https://github.com/Airscripts/blog/tree/main/content"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
