[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.101.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.staging]
command = "hugo --gc --minify --enableGitInfo"

[context.staging.environment]
HUGO_VERSION = "0.101.0"
HUGO_ENV = "production"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200