version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.3.1
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          name: workflows
          base-revision: main
          resource_class: small
          config-path: .circleci/workflows.yml

          mapping: |
            data/.* build true
            i18n/.* build true
            tests/.* tests true
            static/.* build true
            content/.* build true
            layouts/.* build true
            resources/.* build true
            archetypes/.* build true
            config.toml/.* build true
            
      - continuation/continue:
          configuration_path: .circleci/workflows.yml

          parameters: '{
            "build": false,
            "tests": false,
            "deploy": false,
            "verify": false
          }'

          filters:
            tags:
              only:
                - /.*/

            branches:
              ignore: /.*/
